# db-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-quotes-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-quotes-db
  template:
    metadata:
      labels:
        app: vehicle-quotes-db
    spec:
      containers:
        - name: vehicle-quotes-db
          image: postgres:13
          ports:
            - containerPort: 5432
              name: "postgres"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: vehicle-quotes-postgres-data-storage
          env:
            - name: POSTGRES_DB
              value: vehicle_quotes
            - name: POSTGRES_USER
              value: vehicle_quotes
            - name: POSTGRES_PASSWORD
              value: password
          resources:
            limits:
              memory: 4Gi
              cpu: "2"
      volumes:
        - name: vehicle-quotes-postgres-data-storage
          persistentVolumeClaim:
            claimName: vehicle-quotes-postgres-data-persisent-volume-claim
            