# Create the SQL Server deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-quotes-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-quotes-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vehicle-quotes-db
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/rhel/server:2019-latest
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: SA_PASSWORD
          volumeMounts:
            - name: vehicle-quotes-postgres-data-storage
              mountPath: /var/opt/mssql
          resources:
            requests:
              memory: "2GB"
              cpu: "500m"
            limits:
              memory: "4GB"
              cpu: "1000m"
      volumes:
        - name: vehicle-quotes-postgres-data-storage
          persistentVolumeClaim:
            claimName: vehicle-quotes-postgres-data-persisent-volume-claim
