apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  namespace: unitaire
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1000m"
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "yourStrong(!)Password"
            - name: Database
              value: GC.WebReact
          volumeMounts:
            - name: mssqldb
              mountPath: /var/opt/mssql/datas
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: mssql-data-claim

            # "Server=172.17.0.2;Database=GC.WebReact;User Id=SA;Password=yourStrong(!)Password;MultipleActiveResultSets=true"
