# web-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: service-webreact
spec:
  type: NodePort
  selector:
    app: gc.webreact
  ports:
    - name: "http"
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
    - name: "https"
      protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30001
