# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: "unitaire"

---
apiVersion: v1
kind: Namespace
metadata:
  name: "acceptation"

---
apiVersion: v1
kind: Namespace
metadata:
  name: "production"


---
# Secret unitaire
apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: "unitaire"
type: Opaque
data:
  connection_string: U2VydmVyPW1zc3FsO0RhdGFiYXNlPUdDLldlYlJlYWN0O1VzZXIgSWQ9U0E7UGFzc3dvcmQ9eW91clN0cm9uZyghKVBhc3N3b3JkO011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz10cnVl
  MSSQL_SA_PASSWORD: eW91clN0cm9uZyghKVBhc3N3b3Jk

---
# Secret acceptation
apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: "acceptation"
type: Opaque
data:
  connection_string: U2VydmVyPW1zc3FsO0RhdGFiYXNlPUdDLldlYlJlYWN0O1VzZXIgSWQ9U0E7UGFzc3dvcmQ9eW91clN0cm9uZyghKVBhc3N3b3JkO011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz10cnVl
  MSSQL_SA_PASSWORD: eW91clN0cm9uZyghKVBhc3N3b3Jk

---
# Secret production
apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: "production"
type: Opaque
data:
  connection_string: U2VydmVyPW1zc3FsO0RhdGFiYXNlPUdDLldlYlJlYWN0O1VzZXIgSWQ9U0E7UGFzc3dvcmQ9eW91clN0cm9uZyghKVBhc3N3b3JkO011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz10cnVl
  MSSQL_SA_PASSWORD: eW91clN0cm9uZyghKVBhc3N3b3Jk

---
# Configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
  namespace: "unitaire"
data:
  PersistentVolume_mssqldb: "/run/desktop/mnt/host/c/itv/ITV-TP3-DL-JPD/persistence/unitaire"
  nodePort: "30000"

---
# service for webreact - unitaire
apiVersion: v1
kind: Service
metadata:
  name: webreact
  namespace: "unitaire"
spec:
  type: NodePort # type of service
  selector:
    app: GC.WebReact
  ports:
    - name: http
      protocol: TCP
      port: 80 # port exposed internally by the service
      targetPort: 80 # port exposed by the container
      nodePort: 30000 # port accessible from outside the cluster

---
# service for webreact - production
apiVersion: v1
kind: Service
metadata:
  name: webreact
  namespace: "production"
spec:
  type: NodePort # type of service
  selector:
    app: GC.WebReact
  ports:
    - name: http
      protocol: TCP
      port: 80 # port exposed internally by the service
      targetPort: 80 # port exposed by the container
      nodePort: 30002 # port accessible from outside the cluster

---
# service for webreact - acceptation
apiVersion: v1
kind: Service
metadata:
  name: webreact
  namespace: "acceptation"
spec:
  type: NodePort # type of service
  selector:
    app: GC.WebReact
  ports:
    - name: http
      protocol: TCP
      port: 80 # port exposed internally by the service
      targetPort: 80 # port exposed by the container
      nodePort: 30001 # port accessible from outside the cluster

---
# PV - unitaire
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssqldb-unitaire
  labels:
    type: local
spec:
  claimRef:
    namespace: unitaire
    name: mssql-data-claim
  storageClassName: manual
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/itv/ITV-TP3-DL-JPD/persistence/unitaire"

---
# PV - production
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssqldb-production
  labels:
    type: local
spec:
  claimRef:
    namespace: production
    name: mssql-data-claim
  storageClassName: manual
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/itv/ITV-TP3-DL-JPD/persistence/production"

---
# PV - Acceptation
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssqldb-acceptation
  labels:
    type: local
spec:
  claimRef:
    namespace: acceptation
    name: mssql-data-claim
  storageClassName: manual
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/itv/ITV-TP3-DL-JPD/persistence/acceptation"


---
# PVC - unitaire
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: unitaire
  name: mssql-data-claim
spec:
  volumeName: mssqldb-unitaire
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# PVC - production
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: production
  name: mssql-data-claim
spec:
  volumeName: mssqldb-production
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# PVC - acceptation
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: acceptation
  name: mssql-data-claim
spec:
  volumeName: mssqldb-acceptation
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
