apiVersion: v1
kind: Namespace
metadata:
  name: "unitaire"

---
apiVersion: v1
kind: Namespace
metadata:
  name: "acceptation"

---
apiVersion: v1
kind: Namespace
metadata:
  name: "production"


---


apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: "unitaire"
type: Opaque
data:
  connection_string: U2VydmVyPW1zc3FsO0RhdGFiYXNlPUdDLldlYlJlYWN0O1VzZXIgSWQ9U0E7UGFzc3dvcmQ9eW91clN0cm9uZyghKVBhc3N3b3JkO011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz10cnVl
  MSSQL_SA_PASSWORD: eW91clN0cm9uZyghKVBhc3N3b3Jk
---

apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: "acceptation"
type: Opaque
data:
  connection_string: U2VydmVyPW1zc3FsO0RhdGFiYXNlPUdDLldlYlJlYWN0O1VzZXIgSWQ9U0E7UGFzc3dvcmQ9eW91clN0cm9uZyghKVBhc3N3b3JkO011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz10cnVl
  MSSQL_SA_PASSWORD: eW91clN0cm9uZyghKVBhc3N3b3Jk
---

apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: "production"
type: Opaque
data:
  connection_string: U2VydmVyPW1zc3FsO0RhdGFiYXNlPUdDLldlYlJlYWN0O1VzZXIgSWQ9U0E7UGFzc3dvcmQ9eW91clN0cm9uZyghKVBhc3N3b3JkO011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz10cnVl
  MSSQL_SA_PASSWORD: eW91clN0cm9uZyghKVBhc3N3b3Jk




---
# db-persistent-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssqldb-unitaire
  labels:
    type: local
spec:
  claimRef:
    namespace: unitaire
    name: mssql-data-claim
  storageClassName: manual
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/itv/ITV-TP3-DL-JPD/persistence/unitaire"

---
# db-persistent-volume-claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: unitaire
  name: mssql-data-claim
spec:
  volumeName: mssqldb-unitaire
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
